### ISSUE TITLE
Правки до ДЗ 22

### ISSUE THREAD

**Issue by Dexter19** [AnnaKashyra/AnnaKashyra.github.io#1]
1. Отримати всі елементи з тегом h1. Вивести на консоль тип отриманого об'єкту та його розмір. Використовуючи цикл for, вивести на консоль кожний елемент з отриманого об'єкту.
Ось рішення за допомогою цикла for. У вас for of теж правильно, але в умові написани викорситовувати цикл for.
```
const allTitles = document.getElementsByTagName('h1')

console.log(allTitles) //HTMLCollections
console.log(allTitles.length) // 4

for (let i = 0; i < allTitles.length; i++) {
  console.log(allTitles[i]) // prints each elements in the HTMLCollection
}
```
----------------------

**Comment by AnnaKashyra** [comment]
Дякую за перевірку!) Я зауважила, що в умові завдання вказаний цикл for, але оскільки в лекції тренер використовував цикл for ... of, вирішила зробити так само
